/**
 * Procedures that ship with the app, rather than being taught to it.
 *
 * The gap these fill is real and was easy to miss. `create_file` can write a
 * .docx, a .xlsx and a .pptx, and its description says so — but the *conventions*
 * are not in the description, because a description long enough to hold them would
 * be thousands of tokens on every single request. So the model knew it could make a
 * spreadsheet and did not know that a heading above a table starts a new sheet, or
 * that a blockquote under a slide becomes the speaker notes.
 *
 * That is exactly the shape a skill already solves: the menu is cheap, the
 * instructions are read only when they apply. These are the same mechanism as the
 * skills a user writes, with two differences — they cannot be edited or deleted,
 * and they are the same on every deployment.
 *
 * The menu is what decides whether one gets read, so each `description` is written
 * about the *situation* ("asked for a report, a contract, a letter") rather than
 * about the contents.
 */
export const BUILTIN_SKILLS = [
  {
    id: 'builtin:docx',
    name: 'Writing a Word document',
    description:
      'When asked for a report, a contract, a letter, a proposal, meeting minutes, a CV — anything whose home is Word. Read before calling create_file with format docx.',
    instructions: [
      '# Writing a Word document',
      '',
      'You write **Markdown**; the converter turns it into real Word markup. So the',
      'question is never "how do I make a heading in docx" — it is "what Markdown do I',
      'write", and the answer is ordinary Markdown.',
      '',
      '## What carries across',
      '',
      '- `#` to `######` become Word heading styles, so the document gets a real',
      '  navigation pane and a table of contents that works.',
      '- `**bold**`, `*italic*`, `` `code` ``, links, and nested lists all carry.',
      '- Pipe tables become Word tables with a header row.',
      '- `---` on its own line becomes a page break. This is the one people forget,',
      '  and it is what separates a covering letter from the thing it covers.',
      '- A blockquote becomes an indented quotation block.',
      '',
      '## Structure that makes it look professional',
      '',
      '1. **One `#` at the top, and only one.** That is the document title. Several',
      '   competing H1s is the most common way a generated document looks generated.',
      '2. **Pass `title`** as well, separately — it sets the file\'s own properties, which',
      'is what Word shows in its title bar and what a document management system indexes.',
      '3. Go down a level at a time. An `###` directly under an `#` reads as a mistake in',
      '   the navigation pane even when the text is fine.',
      '4. Numbers belong in a table, not in a sentence. Three figures in prose is three',
      '   figures somebody has to re-read; a three-row table is a glance.',
      '',
      '## Language',
      '',
      'Write in the language the user asked in, including the headings. A Vietnamese',
      'report with English section titles is the thing that gets noticed first, and the',
      'accents come out correctly — the converter is UTF-8 throughout.',
      '',
      '## What not to do',
      '',
      '- **Do not paste the document into your reply as well.** It is a file; the user',
      '  opens it. Repeating it doubles the tokens and gives them two versions to confuse.',
      '- **Do not make a second file to change one number.** `update_file` on the same id',
      '  keeps one document with a version history. A second nearly-identical quotation is',
      '  how the wrong one gets sent to a client.',
      '- Do not ask for a PDF and apologise. Make the .docx and tell them the viewer has',
      '  Print → Save as PDF, or use `export_pdf` if a PDF on disk is what they want.',
    ].join('\n'),
  },
  {
    id: 'builtin:xlsx',
    name: 'Building a spreadsheet',
    description:
      'When asked for a spreadsheet, a budget, a price list, a tracker, a table of figures, or anything with several sheets. Read before calling create_file with format xlsx or csv.',
    instructions: [
      '# Building a spreadsheet',
      '',
      'Two ways in, and the choice matters more than it looks.',
      '',
      '## Markdown tables — for anything a person will read',
      '',
      'Write pipe tables. **A heading above a table starts a new sheet, and the heading',
      'becomes the sheet name.** That is the whole mechanism for a multi-sheet workbook:',
      '',
      '```',
      '## Revenue',
      '| Month | Amount |',
      '|---|---|',
      '| January | 12,000,000 |',
      '',
      '## Costs',
      '| Month | Amount |',
      '|---|---|',
      '| January | 8,400,000 |',
      '```',
      '',
      'That is two sheets called Revenue and Costs, not one sheet with a gap in it.',
      '',
      '## JSON — when the shape is awkward',
      '',
      '`{"sheets":[{"name":"Revenue","rows":[["Month","Amount"],["January",12000000]]}]}`',
      '',
      'Use this when a cell contains a pipe character, or when the data is already',
      'structured and re-rendering it as Markdown would only be a chance to make a',
      'transcription error.',
      '',
      '## Getting the numbers right',
      '',
      '- **Write numbers as numbers.** `12000000`, not `"12,000,000"` and not `"12 triệu"`.',
      '  A number stored as text cannot be summed, and the user will discover that when',
      '  they try — which is the moment the spreadsheet stops being useful.',
      '- Currency and units belong in the **column heading**, not in every cell.',
      '  `Amount (VND)` once beats `₫` twelve times.',
      '- Dates as `YYYY-MM-DD`. Every locale reads that the same way; `03/04` does not.',
      '- One header row, and make it say something. `Column1` is not a heading.',
      '',
      '## Totals',
      '',
      'Put a total row in when the columns are numbers — it is the first thing anybody',
      'looks for. Compute it yourself and write the value; a formula string would arrive',
      'as text rather than as a formula.',
      '',
      '## For csv',
      '',
      'Same tables, but only the first one is used — a CSV file has exactly one sheet.',
      'If the data genuinely needs several, say so and make an xlsx instead.',
    ].join('\n'),
  },
  {
    id: 'builtin:pptx',
    name: 'Making a slide deck',
    description:
      'When asked for a deck, a presentation, slides, a pitch, or a training session. Read before calling create_file with format pptx.',
    instructions: [
      '# Making a slide deck',
      '',
      'The mapping is simple and worth knowing exactly:',
      '',
      '- **Each heading is a new slide**, and the heading is the slide title.',
      '- **The list under it is that slide\'s bullets.**',
      '- **A blockquote (`>`) becomes the speaker notes** for that slide — visible to',
      '  the presenter, not to the room.',
      '',
      '```',
      '# Q3 results',
      '- Revenue up 18%',
      '- Two new enterprise accounts',
      '> Open with the revenue number, then hand to Mai for the accounts.',
      '```',
      '',
      '## What makes a deck usable rather than merely correct',
      '',
      '1. **Six bullets is the ceiling, and four is better.** A slide is a thing glanced',
      '   at while somebody talks. Anything denser belongs in the notes, or in a document.',
      '2. **A bullet is a phrase, not a sentence.** "Revenue up 18%" — not "Our revenue',
      '   has increased by eighteen percent compared to the same quarter last year."',
      '   The full sentence goes in the notes, where it is the script.',
      '3. **Write the notes.** A deck with no notes is a deck somebody has to reconstruct',
      '   the argument for. This is the single thing that most often separates a deck that',
      '   gets used from one that gets rewritten.',
      '4. **A title slide first**, then the content. One heading with no bullets under it',
      '   is a title slide.',
      '5. **Ten to fifteen slides** for an ordinary presentation. Forty short slides is',
      '   not thoroughness, it is a document that has been cut up.',
      '',
      '## What this cannot do',
      '',
      'No images, no charts, no themes, no transitions — it writes text slides with',
      'proper structure. Say that plainly rather than promising a designed deck. If they',
      'need a chart on a slide, `show_widget` can draw one in the conversation for them to',
      'screenshot, or `generate_image` can make a picture they place themselves.',
    ].join('\n'),
  },
  {
    id: 'builtin:pdf',
    name: 'Producing a PDF',
    description:
      'When the user specifically asks for a PDF — an invoice, a quotation, a certificate, anything to be printed or sent as final. Read before promising or refusing one.',
    instructions: [
      '# Producing a PDF',
      '',
      '`create_file` does **not** write PDFs. There are two real routes, and they are for',
      'different situations. Pick deliberately rather than apologising.',
      '',
      '## A PDF on their computer — `export_pdf`',
      '',
      'Needs their computer connected. Give it `html` and a path, and it prints through',
      'the browser on that machine, which means the system fonts — so Vietnamese',
      'diacritics and any non-Latin script come out correct. That is the reason to go',
      'through a browser rather than compose a PDF directly.',
      '',
      'Write one self-contained page: inline `<style>`, no external fonts or images.',
      '`landscape: true` for a wide table.',
      '',
      'For an invoice or a quotation this is the right answer. Lay it out properly — a',
      'header with the business details, a table of line items, a total that stands out,',
      'payment terms at the foot.',
      '',
      '## A document they can print themselves — `create_file`',
      '',
      'No computer connected, or they will want to edit it: make a `.docx` and tell them',
      'the viewer has **Print → Save as PDF**. That goes through their own browser, which',
      'also has the fonts.',
      '',
      '## Do not',
      '',
      '- Do not claim to have made a PDF when you made a .docx. Name the file you made.',
      '- Do not write a `.pdf` file with `write_file`. The bytes would not be a PDF, and',
      '  the failure arrives when they try to open it.',
    ].join('\n'),
  },
  {
    id: 'builtin:artifact',
    name: 'Building a small tool or page',
    description:
      'When asked for a calculator, a dashboard, a form, a chart, a mock-up, a game, or any small thing they want to use rather than read. Read before calling create_file with format html.',
    instructions: [
      '# Building a small tool or page',
      '',
      '`create_file` with `format: "html"` and real markup makes something the user can',
      '**run** in the conversation. This is the right answer far more often than it gets',
      'used: a budget calculator beats a table of worked examples, and an interactive',
      'chart beats a description of a trend.',
      '',
      '## The constraints, which are absolute',
      '',
      'It runs in a sandboxed frame with **no network and no access to their session**.',
      'So:',
      '',
      '- One file. Inline every style and every script.',
      '- No CDN, no external fonts, no `fetch`, no images by URL. A remote script does not',
      '  fail loudly — it silently does nothing, and you get a blank page with no clue why.',
      '- Draw pictures with inline SVG or a `<canvas>`.',
      '- **`localStorage` throws**, because the frame has an opaque origin. Do not reach',
      '  for it. Hold state in a variable; if it genuinely has to survive being closed,',
      '  say so plainly rather than writing storage code that will throw on first use.',
      '',
      '## Making it good rather than merely working',
      '',
      '1. **Work on a phone.** Most people open this on one. Use flexbox or grid, relative',
      '   units, and tap targets big enough for a thumb.',
      '2. **Dark and light.** The app follows the system theme and the frame is transparent,',
      '   so a hard-coded white background is a white rectangle in a dark conversation.',
      '   Set both explicitly, or use `@media (prefers-color-scheme: dark)`.',
      '3. **No dead space.** A form with four fields should not be four fields floating in',
      '   a screen of nothing. Size the layout to the content.',
      '4. **Label everything.** A `<label>` per input, real `<button>` elements, and a',
      '   visible focus ring. It has to be usable by keyboard.',
      '5. **Show the answer as it is typed.** A calculator with a Calculate button is a',
      '   calculator that feels older than it is.',
      '',
      '## Which tool',
      '',
      '- Something they will **use** → `create_file`, format html. It is a file: it lives',
      '  in Artifacts, it survives, they can come back to it.',
      '- Something to **look at once**, inside your explanation → `show_widget`. Inline,',
      '  no scripting, gone from mind once read.',
    ].join('\n'),
  },
];

export const BUILTIN_BY_ID = new Map(BUILTIN_SKILLS.map((skill) => [skill.id, skill]));

/** Matched loosely, so a model that types the name rather than the id still lands. */
export function findBuiltinSkill(name) {
  const wanted = String(name || '').trim().toLowerCase();
  if (!wanted) return null;
  return (
    BUILTIN_BY_ID.get(wanted) ||
    BUILTIN_SKILLS.find((skill) => skill.id.toLowerCase() === wanted) ||
    BUILTIN_SKILLS.find((skill) => skill.name.toLowerCase() === wanted) ||
    // "docx", "xlsx", "pdf" — what somebody would actually type.
    BUILTIN_SKILLS.find((skill) => skill.id.split(':')[1] === wanted) ||
    null
  );
}
